headFirstLabel=Рейтинговое
headSecondLabel=Популярное
headThirdLabel=Новое
headFourLabel=Лента
headerplaceholder=Найти что-либо
footerlogin=Вход
footersignin=Регистрация
footerabout=About
footerhello=Привет
footerlogout=Выйти
refreshNotif=Обновить
emptyNotifList=Нет элементов для отображения.
January=Января
February=Февраля
March=Марта
April=Апреля
May=Мая
June=Июня
July=Июля
August=Августа
September=Сентября
October=Октября
November=Ноября
December=Декабря
date_on=в
notif_accessDenied=Для совершения этого действия нужно войти.
notif_requestError=Во время обработки запроса произошла ошибка.
messageSentError=Ошибка при отправке сообщения. Максимально возможное число символов: