writeALetterButton=Написать сообщение
addToFriendButton=Добавить в друзья
eventLabel=События
friendsLabel=Друзья
writeToaFriendLabel=Написать сообщение
friendSinceLabel=В друзьях с 
acceptButton=Принять
declineButton=Отклонить
regDateLabel=Присоединился
blockedLabel=Статус
popLabel=Популярность
roleLabel=Роль
ratingLabel=Рейтинг
aboutYourselfLabel=Несколько слов о себе
commentsLabel=Комментарии
hisCommentsLabel=Его комментарии
followersLabel=Подписчики
userLabel=Участник
hisMaterials=Его материалы
hisLikes=Понравившиесе
sendButton=Отправить
dateLabel=Дата
requestIsSended=Запрос отправлен
requestReturnedException=Попробуйте ещё раз
duplicateRequest=Запрос уже был отправлен
alreadyFriends=Вы уже в друзьях.
noFriends=Нет данных для показа.
askForFriend=Хочет быть добавленным в друзья
friendsFromNow=Теперь вы друзья с 
friendsFail=Что-то пошло не так...
friendsDeleteSucc=Вы более не друзья с
noEvents=Нет элементов для отображения.
friendsDeslSuccess=Вы отклонили заявку
userWasBlocked=Заблокирован
userWasNotBlocked=Активен
roleUser=Пользователь
roleRoot=root
roleEmployee=Модератор
nothingAbout=Этот пользователь пока ничего о себе не рассказал
backButton=Назад
byAlphabet=По алфавиту
byDate=По дате
byRating=По рейтингу
byPop=По популярности
fflDelete=Удалить из друзей
loadMore=Загрузить ещё
felFrom=От 
felSince=Получено:
felMessage=Ниже будет список ваших уведомлений
prefsButton=Настройки